# Project: algo3
# Makefile created by Steve Chang
# Date modified: 2024.02.25

LIBNAME = libcrc.a

DIR = crc

SUBDIR =

INCLUDE =

SRCS = $(wildcard *.c)

OBJDIR = obj

include $(MAKE_RULES)
