# Project: aardvark
# Makefile created by Steve Chang
# Date modified: 2024.06.22

LIBNAME = libnvme.a

DIR = nvme

SUBDIR =

INCLUDE = \
	aardvark \
	crc \
	smbus \
	utility \
	mctp \

SRCS = $(wildcard *.$(C_FILE_EXT))

OBJDIR = obj

ASMDIR = asm

include $(MAKE_RULES)
