# Project: aardvark
# Makefile created by Steve Chang
# Date modified: 2024.06.22

LIBNAME = libi2c.a

DIR = smbus

SUBDIR =

INCLUDE = \
	aardvark \
	crc \
	utility \
	smbus \

SRCS = $(wildcard *.$(C_FILE_EXT))

OBJDIR = obj

ASMDIR = asm

include $(MAKE_RULES)
