# Project: aardvark
# Makefile created by Steve Chang
# Date modified: 2024.04.12

LIBNAME = libsmbus.a

DIR = smbus

SUBDIR =

INCLUDE = \
	aardvark \
	crc \
	utility \

SRCS = $(wildcard *.c)

OBJDIR = obj

include $(MAKE_RULES)
