# Project: aardvark
# Makefile created by Steve Chang
# Date modified: 2024.06.22

LIBNAME = libsmbus.a

DIR = smbus

SUBDIR =

INCLUDE = \
	aardvark \
	crc \
	utility \

SRCS = $(wildcard *.$(C_FILE_EXT))

include $(MAKE_RULES)
