# Project: aardvark
# Makefile created by Steve Chang
# Date modified: 2024.06.22

LIBNAME = libmctp.a

DIR = mctp

SUBDIR =

INCLUDE = \
	aardvark \
	crc \
	smbus \
	utility \

SRCS = $(wildcard *.c)

OBJDIR = obj

ASMDIR = asm

include $(MAKE_RULES)
