# Project: aardvark
# Makefile created by Steve Chang
# Date modified: 2024.04.12

LIBNAME = libmctp.a

DIR = mctp

SUBDIR =

INCLUDE = \
	aardvark \
	crc \
	smbus \
	utility \

SRCS = $(wildcard *.c)

OBJDIR = obj

include $(MAKE_RULES)
