# Project: aardvark
# Makefile created by Steve Chang
# Date modified: 2024.06.22

LIBNAME = libaardvark.a

DIR = aardvark

SUBDIR =

INCLUDE = crc \

SRCS = $(wildcard *.c)

OBJDIR = obj

ASMDIR = asm

include $(MAKE_RULES)
