# Project: algo3
# Makefile created by Steve Chang
# Date modified: 2024.04.03

LIBNAME = libaardvark.a

DIR = aardvark

SUBDIR =

INCLUDE =

SRCS = $(wildcard *.c)

OBJDIR = obj

include $(MAKE_RULES)
