# Project: aardvark
# Makefile created by Steve Chang
# Date modified: 2024.06.22

LIBNAME = libmain.a

DIR = src

SUBDIR =

INCLUDE = \
	checksum \
	crc \
	utility \
	aardvark \
	smbus \
	mctp \

SRCS = $(wildcard *.$(C_FILE_EXT))

OBJDIR = obj

ASMDIR = asm

include $(MAKE_RULES)
