# Project: aardvark
# Makefile created by Steve Chang
# Date modified: 2024.06.22

LIBNAME = libchecksum.a

DIR = checksum

SUBDIR =

INCLUDE =

SRCS = $(wildcard *.$(C_FILE_EXT))

include $(MAKE_RULES)
